model:
  name: diffusion

task:
  name: diffusion
  max_steps: 2_000
  train_dl:
    batch_size: 512

optimizer:
  name: adam
  lr: 0.001

lr_scheduler:
  name: cosine_decay

trainer:
  name: sl
  validation:
    valid_every_n_steps: 250

logger:
  - name: stdout
  - name: tensorboard

launcher:
  name: mp
