model:
  name: unet
  in_dim: 1
  embed_dim: 128
  dim_scales: [1, 2, 4, 8]

task:
  name: mnist
  max_steps: 10_000
  train_dl:
    batch_size: 16

optimizer:
  name: adam
  lr: 3e-4

lr_scheduler:
  name: linear

trainer:
  name: sl
  compiler:
    model: false
    func: false

logger:
  - name: stdout
  - name: tensorboard

launcher:
  name: mp
