model:
  name: unet-diffusion
  in_dim: 1
  embed_dim: 128
  dim_scales: [1, 2, 4, 8]

task:
  name: mnist-diffusion
  max_steps: 2_000
  train_dl:
    batch_size: 512

optimizer:
  name: adam
  lr: 0.001

lr_scheduler:
  name: cosine_decay

trainer:
  name: sl
  compiler:
    model: false
    func: false

logger:
  - name: stdout
  - name: tensorboard

launcher:
  name: mp
